name: mcp-prompts-test-environment

services:
  # PostgreSQL database for testing
  postgres-test:
    image: postgres:14-alpine
    container_name: mcp-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp_prompts_test
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Test runner service
  mcp-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: mcp-test-runner
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - STORAGE_TYPE=postgres
      - PG_HOST=postgres-test
      - PG_PORT=5432
      - PG_DATABASE=mcp_prompts_test
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_SSL=false
      - TEST_INTEGRATION=true
    volumes:
      - ./test-results:/app/test-results
    command: npm test 