services:
  mcp-prompts:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    environment:
      - MODE=mcp
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    # MCP servers typically don't need exposed ports for stdio communication
    # but we can expose for health checks if needed
    ports:
      - "3003:3003"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3003/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s