version: '3.8'

services:
  mcp-prompts:
    build: .
    volumes:
      - ./prompts:/app/prompts
    environment:
      - STORAGE_TYPE=file
      - PROMPTS_DIR=/app/prompts
      - LOG_LEVEL=info
    stdin_open: true
    tty: true

  filesystem-server:
    image: node:18-alpine
    command: npx -y @modelcontextprotocol/server-filesystem /prompts
    volumes:
      - ./prompts:/prompts

  memory-server:
    image: node:18-alpine
    command: npx -y @modelcontextprotocol/server-memory
    volumes:
      - ./data:/data

  github-server:
    image: node:18-alpine
    command: npx -y @modelcontextprotocol/server-github
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN:-} 