version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:14
    container_name: mcp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp_prompts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MCP Prompts Server
  mcp-prompts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-prompts
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mcp_prompts
      - STORAGE_TYPE=file
      - PROMPTS_DIR=/app/prompts
      - PORT=3000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
    volumes:
      - ./config:/app/config
      - ./prompts:/app/prompts
      - ./logs:/app/logs
    command: ["docker/startup.sh"]
    stdin_open: true
    tty: true

volumes:
  postgres_data: 