services:
  mcp-prompts:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3003
      - MODE=http
      - STORAGE_TYPE=memory
      - PROMPTS_DIR=/app/data
    volumes:
      - ./data:/app/data
    ports:
      - "3003:3003"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

