services:
  mcp-prompts-file:
    build:
      context: .
      dockerfile: Dockerfile.file
    environment:
      - HOST=0.0.0.0
      - PORT=3003
      - MODE=mcp
      - STORAGE_TYPE=file
      - PROMPTS_DIR=/app/data
    volumes:
      - ./data:/app/data
    ports:
      - "3003:3003"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3003/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

