# pnpm workspace configuration - optimized for all packages and apps
packages:
  # Main package directories
  - 'packages/*'
  - 'packages/@sparesparrow/*'
  - 'apps/*'
  - 'docs'
  
  # Exclude build artifacts, cache, and temporary files
  - '!**/dist'
  - '!**/build'
  - '!**/.cache'
  - '!**/node_modules'
  - '!**/*.tmp'
  - '!**/*.temp'
  - '!**/coverage'
  - '!**/.nyc_output'
  - '!**/.next'
  - '!**/.nuxt'
  - '!**/.output'
  - '!**/.vercel'
