packages:
  - 'packages/core'
  - 'packages/adapters-file'
  - 'packages/adapters-postgres'
  - 'packages/adapters-memory'
  - 'packages/adapters-mdc'
  - 'packages/adapters-eta'
  - 'packages/adapters-mcp'
  - 'packages/adapters-rest'
  - 'packages/adapters-cli'
  - 'apps/server'
  - 'docs'
  - 'packages/mcp-prompts-catalog'
  - 'packages/mcp-prompts-contracts'
