name: mcp-prompts-postgres

services:
  # PostgreSQL database service
  postgres:
    image: postgres:14
    container_name: mcp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp_prompts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # MCP Prompts server with PostgreSQL storage
  mcp-prompts:
    image: sparesparrow/mcp-prompts:latest
    container_name: mcp-prompts-pg
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - STORAGE_TYPE=postgres
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@postgres:5432/mcp_prompts
      - PROMPTS_DIR=/app/data/prompts
      - BACKUPS_DIR=/app/data/backups
      - LOG_LEVEL=info
      - HTTP_SERVER=true
      - PORT=3003
      - HOST=0.0.0.0
    volumes:
      - prompts_data:/app/data
    ports:
      - "3003:3003"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

volumes:
  postgres_data:
    name: mcp-postgres-data
  prompts_data:
    name: mcp-prompts-data 