import { z } from 'zod';
/**
 * Zod schema for all supported environment variables.
 * Uses .coerce for numbers/booleans, provides defaults, and enforces required fields.
 */
export declare const EnvSchema: z.ZodObject<{
    BACKUPS_DIR: z.ZodDefault<z.ZodString>;
    CORS_ORIGIN: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_INDEX: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_NODE: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_PASSWORD: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_SEQUENCE_INDEX: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_USERNAME: z.ZodOptional<z.ZodString>;
    ELEVENLABS_API_KEY: z.ZodOptional<z.ZodString>;
    ELEVENLABS_CACHE_DIR: z.ZodOptional<z.ZodString>;
    ELEVENLABS_MODEL_ID: z.ZodOptional<z.ZodString>;
    ELEVENLABS_OPTIMIZATION_LEVEL: z.ZodOptional<z.ZodEnum<["speed", "quality", "balanced"]>>;
    ELEVENLABS_SIMILARITY_BOOST: z.ZodOptional<z.ZodNumber>;
    ELEVENLABS_SPEAKER_BOOST: z.ZodOptional<z.ZodBoolean>;
    ELEVENLABS_STABILITY: z.ZodOptional<z.ZodNumber>;
    ELEVENLABS_STYLE: z.ZodOptional<z.ZodNumber>;
    ELEVENLABS_USE_CACHING: z.ZodOptional<z.ZodBoolean>;
    ELEVENLABS_VOICE_ID: z.ZodOptional<z.ZodString>;
    ENABLE_SSE: z.ZodOptional<z.ZodBoolean>;
    HOST: z.ZodDefault<z.ZodString>;
    HTTP_SERVER: z.ZodDefault<z.ZodBoolean>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["debug", "info", "warn", "error"]>>;
    MCP_SERVER: z.ZodDefault<z.ZodBoolean>;
    MDC_BACKUP_ENABLED: z.ZodOptional<z.ZodBoolean>;
    MDC_BACKUP_INTERVAL: z.ZodOptional<z.ZodNumber>;
    MDC_RULES_DIR: z.ZodOptional<z.ZodString>;
    NAME: z.ZodDefault<z.ZodString>;
    PORT: z.ZodDefault<z.ZodNumber>;
    POSTGRES_DATABASE: z.ZodOptional<z.ZodString>;
    POSTGRES_HOST: z.ZodOptional<z.ZodString>;
    POSTGRES_MAX_CONNECTIONS: z.ZodOptional<z.ZodNumber>;
    POSTGRES_PASSWORD: z.ZodOptional<z.ZodString>;
    POSTGRES_PORT: z.ZodOptional<z.ZodNumber>;
    POSTGRES_SSL: z.ZodOptional<z.ZodBoolean>;
    POSTGRES_USER: z.ZodOptional<z.ZodString>;
    PROMPTS_DIR: z.ZodDefault<z.ZodString>;
    SEQUENCES_MAX_STEPS: z.ZodOptional<z.ZodNumber>;
    SEQUENCES_RETRY_ATTEMPTS: z.ZodOptional<z.ZodNumber>;
    SEQUENCES_TIMEOUT: z.ZodOptional<z.ZodNumber>;
    SSE_PATH: z.ZodOptional<z.ZodString>;
    STORAGE_TYPE: z.ZodDefault<z.ZodEnum<["file", "postgres", "memory", "mdc", "elasticsearch"]>>;
    STREAMING_CHUNK_SIZE: z.ZodOptional<z.ZodNumber>;
    STREAMING_ENABLED: z.ZodOptional<z.ZodBoolean>;
    STREAMING_MAX_TOKENS: z.ZodOptional<z.ZodNumber>;
    VERSION: z.ZodDefault<z.ZodString>;
    redis: z.ZodOptional<z.ZodObject<{
        db: z.ZodOptional<z.ZodNumber>;
        host: z.ZodOptional<z.ZodString>;
        password: z.ZodOptional<z.ZodString>;
        port: z.ZodOptional<z.ZodNumber>;
        ttl: z.ZodOptional<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    }, {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    BACKUPS_DIR: string;
    HOST: string;
    HTTP_SERVER: boolean;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    MCP_SERVER: boolean;
    NAME: string;
    PORT: number;
    PROMPTS_DIR: string;
    STORAGE_TYPE: "file" | "postgres" | "memory" | "mdc" | "elasticsearch";
    VERSION: string;
    CORS_ORIGIN?: string | undefined;
    ELASTICSEARCH_INDEX?: string | undefined;
    ELASTICSEARCH_NODE?: string | undefined;
    ELASTICSEARCH_PASSWORD?: string | undefined;
    ELASTICSEARCH_SEQUENCE_INDEX?: string | undefined;
    ELASTICSEARCH_USERNAME?: string | undefined;
    ELEVENLABS_API_KEY?: string | undefined;
    ELEVENLABS_CACHE_DIR?: string | undefined;
    ELEVENLABS_MODEL_ID?: string | undefined;
    ELEVENLABS_OPTIMIZATION_LEVEL?: "speed" | "quality" | "balanced" | undefined;
    ELEVENLABS_SIMILARITY_BOOST?: number | undefined;
    ELEVENLABS_SPEAKER_BOOST?: boolean | undefined;
    ELEVENLABS_STABILITY?: number | undefined;
    ELEVENLABS_STYLE?: number | undefined;
    ELEVENLABS_USE_CACHING?: boolean | undefined;
    ELEVENLABS_VOICE_ID?: string | undefined;
    ENABLE_SSE?: boolean | undefined;
    MDC_BACKUP_ENABLED?: boolean | undefined;
    MDC_BACKUP_INTERVAL?: number | undefined;
    MDC_RULES_DIR?: string | undefined;
    POSTGRES_DATABASE?: string | undefined;
    POSTGRES_HOST?: string | undefined;
    POSTGRES_MAX_CONNECTIONS?: number | undefined;
    POSTGRES_PASSWORD?: string | undefined;
    POSTGRES_PORT?: number | undefined;
    POSTGRES_SSL?: boolean | undefined;
    POSTGRES_USER?: string | undefined;
    SEQUENCES_MAX_STEPS?: number | undefined;
    SEQUENCES_RETRY_ATTEMPTS?: number | undefined;
    SEQUENCES_TIMEOUT?: number | undefined;
    SSE_PATH?: string | undefined;
    STREAMING_CHUNK_SIZE?: number | undefined;
    STREAMING_ENABLED?: boolean | undefined;
    STREAMING_MAX_TOKENS?: number | undefined;
    redis?: {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    } | undefined;
}, {
    BACKUPS_DIR?: string | undefined;
    CORS_ORIGIN?: string | undefined;
    ELASTICSEARCH_INDEX?: string | undefined;
    ELASTICSEARCH_NODE?: string | undefined;
    ELASTICSEARCH_PASSWORD?: string | undefined;
    ELASTICSEARCH_SEQUENCE_INDEX?: string | undefined;
    ELASTICSEARCH_USERNAME?: string | undefined;
    ELEVENLABS_API_KEY?: string | undefined;
    ELEVENLABS_CACHE_DIR?: string | undefined;
    ELEVENLABS_MODEL_ID?: string | undefined;
    ELEVENLABS_OPTIMIZATION_LEVEL?: "speed" | "quality" | "balanced" | undefined;
    ELEVENLABS_SIMILARITY_BOOST?: number | undefined;
    ELEVENLABS_SPEAKER_BOOST?: boolean | undefined;
    ELEVENLABS_STABILITY?: number | undefined;
    ELEVENLABS_STYLE?: number | undefined;
    ELEVENLABS_USE_CACHING?: boolean | undefined;
    ELEVENLABS_VOICE_ID?: string | undefined;
    ENABLE_SSE?: boolean | undefined;
    HOST?: string | undefined;
    HTTP_SERVER?: boolean | undefined;
    LOG_LEVEL?: "debug" | "info" | "warn" | "error" | undefined;
    MCP_SERVER?: boolean | undefined;
    MDC_BACKUP_ENABLED?: boolean | undefined;
    MDC_BACKUP_INTERVAL?: number | undefined;
    MDC_RULES_DIR?: string | undefined;
    NAME?: string | undefined;
    PORT?: number | undefined;
    POSTGRES_DATABASE?: string | undefined;
    POSTGRES_HOST?: string | undefined;
    POSTGRES_MAX_CONNECTIONS?: number | undefined;
    POSTGRES_PASSWORD?: string | undefined;
    POSTGRES_PORT?: number | undefined;
    POSTGRES_SSL?: boolean | undefined;
    POSTGRES_USER?: string | undefined;
    PROMPTS_DIR?: string | undefined;
    SEQUENCES_MAX_STEPS?: number | undefined;
    SEQUENCES_RETRY_ATTEMPTS?: number | undefined;
    SEQUENCES_TIMEOUT?: number | undefined;
    SSE_PATH?: string | undefined;
    STORAGE_TYPE?: "file" | "postgres" | "memory" | "mdc" | "elasticsearch" | undefined;
    STREAMING_CHUNK_SIZE?: number | undefined;
    STREAMING_ENABLED?: boolean | undefined;
    STREAMING_MAX_TOKENS?: number | undefined;
    VERSION?: string | undefined;
    redis?: {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    } | undefined;
}>;
export type EnvVars = z.infer<typeof EnvSchema>;
export declare const McpConfigSchema: z.ZodObject<{
    BACKUPS_DIR: z.ZodDefault<z.ZodString>;
    CORS_ORIGIN: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_INDEX: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_NODE: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_PASSWORD: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_SEQUENCE_INDEX: z.ZodOptional<z.ZodString>;
    ELASTICSEARCH_USERNAME: z.ZodOptional<z.ZodString>;
    ELEVENLABS_API_KEY: z.ZodOptional<z.ZodString>;
    ELEVENLABS_CACHE_DIR: z.ZodOptional<z.ZodString>;
    ELEVENLABS_MODEL_ID: z.ZodOptional<z.ZodString>;
    ELEVENLABS_OPTIMIZATION_LEVEL: z.ZodOptional<z.ZodEnum<["speed", "quality", "balanced"]>>;
    ELEVENLABS_SIMILARITY_BOOST: z.ZodOptional<z.ZodNumber>;
    ELEVENLABS_SPEAKER_BOOST: z.ZodOptional<z.ZodBoolean>;
    ELEVENLABS_STABILITY: z.ZodOptional<z.ZodNumber>;
    ELEVENLABS_STYLE: z.ZodOptional<z.ZodNumber>;
    ELEVENLABS_USE_CACHING: z.ZodOptional<z.ZodBoolean>;
    ELEVENLABS_VOICE_ID: z.ZodOptional<z.ZodString>;
    ENABLE_SSE: z.ZodOptional<z.ZodBoolean>;
    HOST: z.ZodDefault<z.ZodString>;
    HTTP_SERVER: z.ZodDefault<z.ZodBoolean>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["debug", "info", "warn", "error"]>>;
    MCP_SERVER: z.ZodDefault<z.ZodBoolean>;
    MDC_BACKUP_ENABLED: z.ZodOptional<z.ZodBoolean>;
    MDC_BACKUP_INTERVAL: z.ZodOptional<z.ZodNumber>;
    MDC_RULES_DIR: z.ZodOptional<z.ZodString>;
    NAME: z.ZodDefault<z.ZodString>;
    PORT: z.ZodDefault<z.ZodNumber>;
    POSTGRES_DATABASE: z.ZodOptional<z.ZodString>;
    POSTGRES_HOST: z.ZodOptional<z.ZodString>;
    POSTGRES_MAX_CONNECTIONS: z.ZodOptional<z.ZodNumber>;
    POSTGRES_PASSWORD: z.ZodOptional<z.ZodString>;
    POSTGRES_PORT: z.ZodOptional<z.ZodNumber>;
    POSTGRES_SSL: z.ZodOptional<z.ZodBoolean>;
    POSTGRES_USER: z.ZodOptional<z.ZodString>;
    PROMPTS_DIR: z.ZodDefault<z.ZodString>;
    SEQUENCES_MAX_STEPS: z.ZodOptional<z.ZodNumber>;
    SEQUENCES_RETRY_ATTEMPTS: z.ZodOptional<z.ZodNumber>;
    SEQUENCES_TIMEOUT: z.ZodOptional<z.ZodNumber>;
    SSE_PATH: z.ZodOptional<z.ZodString>;
    STORAGE_TYPE: z.ZodDefault<z.ZodEnum<["file", "postgres", "memory", "mdc", "elasticsearch"]>>;
    STREAMING_CHUNK_SIZE: z.ZodOptional<z.ZodNumber>;
    STREAMING_ENABLED: z.ZodOptional<z.ZodBoolean>;
    STREAMING_MAX_TOKENS: z.ZodOptional<z.ZodNumber>;
    VERSION: z.ZodDefault<z.ZodString>;
    redis: z.ZodOptional<z.ZodObject<{
        db: z.ZodOptional<z.ZodNumber>;
        host: z.ZodOptional<z.ZodString>;
        password: z.ZodOptional<z.ZodString>;
        port: z.ZodOptional<z.ZodNumber>;
        ttl: z.ZodOptional<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    }, {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    }>>;
} & {
    storage: z.ZodObject<{
        database: z.ZodOptional<z.ZodString>;
        host: z.ZodOptional<z.ZodString>;
        maxConnections: z.ZodOptional<z.ZodNumber>;
        password: z.ZodOptional<z.ZodString>;
        port: z.ZodOptional<z.ZodNumber>;
        promptsDir: z.ZodString;
        ssl: z.ZodOptional<z.ZodBoolean>;
        type: z.ZodEnum<["file", "postgres", "memory", "mdc", "elasticsearch"]>;
        user: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: "file" | "postgres" | "memory" | "mdc" | "elasticsearch";
        promptsDir: string;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        database?: string | undefined;
        maxConnections?: number | undefined;
        ssl?: boolean | undefined;
        user?: string | undefined;
    }, {
        type: "file" | "postgres" | "memory" | "mdc" | "elasticsearch";
        promptsDir: string;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        database?: string | undefined;
        maxConnections?: number | undefined;
        ssl?: boolean | undefined;
        user?: string | undefined;
    }>;
}, "strip", z.ZodTypeAny, {
    BACKUPS_DIR: string;
    HOST: string;
    HTTP_SERVER: boolean;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    MCP_SERVER: boolean;
    NAME: string;
    PORT: number;
    PROMPTS_DIR: string;
    STORAGE_TYPE: "file" | "postgres" | "memory" | "mdc" | "elasticsearch";
    VERSION: string;
    storage: {
        type: "file" | "postgres" | "memory" | "mdc" | "elasticsearch";
        promptsDir: string;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        database?: string | undefined;
        maxConnections?: number | undefined;
        ssl?: boolean | undefined;
        user?: string | undefined;
    };
    CORS_ORIGIN?: string | undefined;
    ELASTICSEARCH_INDEX?: string | undefined;
    ELASTICSEARCH_NODE?: string | undefined;
    ELASTICSEARCH_PASSWORD?: string | undefined;
    ELASTICSEARCH_SEQUENCE_INDEX?: string | undefined;
    ELASTICSEARCH_USERNAME?: string | undefined;
    ELEVENLABS_API_KEY?: string | undefined;
    ELEVENLABS_CACHE_DIR?: string | undefined;
    ELEVENLABS_MODEL_ID?: string | undefined;
    ELEVENLABS_OPTIMIZATION_LEVEL?: "speed" | "quality" | "balanced" | undefined;
    ELEVENLABS_SIMILARITY_BOOST?: number | undefined;
    ELEVENLABS_SPEAKER_BOOST?: boolean | undefined;
    ELEVENLABS_STABILITY?: number | undefined;
    ELEVENLABS_STYLE?: number | undefined;
    ELEVENLABS_USE_CACHING?: boolean | undefined;
    ELEVENLABS_VOICE_ID?: string | undefined;
    ENABLE_SSE?: boolean | undefined;
    MDC_BACKUP_ENABLED?: boolean | undefined;
    MDC_BACKUP_INTERVAL?: number | undefined;
    MDC_RULES_DIR?: string | undefined;
    POSTGRES_DATABASE?: string | undefined;
    POSTGRES_HOST?: string | undefined;
    POSTGRES_MAX_CONNECTIONS?: number | undefined;
    POSTGRES_PASSWORD?: string | undefined;
    POSTGRES_PORT?: number | undefined;
    POSTGRES_SSL?: boolean | undefined;
    POSTGRES_USER?: string | undefined;
    SEQUENCES_MAX_STEPS?: number | undefined;
    SEQUENCES_RETRY_ATTEMPTS?: number | undefined;
    SEQUENCES_TIMEOUT?: number | undefined;
    SSE_PATH?: string | undefined;
    STREAMING_CHUNK_SIZE?: number | undefined;
    STREAMING_ENABLED?: boolean | undefined;
    STREAMING_MAX_TOKENS?: number | undefined;
    redis?: {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    } | undefined;
}, {
    storage: {
        type: "file" | "postgres" | "memory" | "mdc" | "elasticsearch";
        promptsDir: string;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        database?: string | undefined;
        maxConnections?: number | undefined;
        ssl?: boolean | undefined;
        user?: string | undefined;
    };
    BACKUPS_DIR?: string | undefined;
    CORS_ORIGIN?: string | undefined;
    ELASTICSEARCH_INDEX?: string | undefined;
    ELASTICSEARCH_NODE?: string | undefined;
    ELASTICSEARCH_PASSWORD?: string | undefined;
    ELASTICSEARCH_SEQUENCE_INDEX?: string | undefined;
    ELASTICSEARCH_USERNAME?: string | undefined;
    ELEVENLABS_API_KEY?: string | undefined;
    ELEVENLABS_CACHE_DIR?: string | undefined;
    ELEVENLABS_MODEL_ID?: string | undefined;
    ELEVENLABS_OPTIMIZATION_LEVEL?: "speed" | "quality" | "balanced" | undefined;
    ELEVENLABS_SIMILARITY_BOOST?: number | undefined;
    ELEVENLABS_SPEAKER_BOOST?: boolean | undefined;
    ELEVENLABS_STABILITY?: number | undefined;
    ELEVENLABS_STYLE?: number | undefined;
    ELEVENLABS_USE_CACHING?: boolean | undefined;
    ELEVENLABS_VOICE_ID?: string | undefined;
    ENABLE_SSE?: boolean | undefined;
    HOST?: string | undefined;
    HTTP_SERVER?: boolean | undefined;
    LOG_LEVEL?: "debug" | "info" | "warn" | "error" | undefined;
    MCP_SERVER?: boolean | undefined;
    MDC_BACKUP_ENABLED?: boolean | undefined;
    MDC_BACKUP_INTERVAL?: number | undefined;
    MDC_RULES_DIR?: string | undefined;
    NAME?: string | undefined;
    PORT?: number | undefined;
    POSTGRES_DATABASE?: string | undefined;
    POSTGRES_HOST?: string | undefined;
    POSTGRES_MAX_CONNECTIONS?: number | undefined;
    POSTGRES_PASSWORD?: string | undefined;
    POSTGRES_PORT?: number | undefined;
    POSTGRES_SSL?: boolean | undefined;
    POSTGRES_USER?: string | undefined;
    PROMPTS_DIR?: string | undefined;
    SEQUENCES_MAX_STEPS?: number | undefined;
    SEQUENCES_RETRY_ATTEMPTS?: number | undefined;
    SEQUENCES_TIMEOUT?: number | undefined;
    SSE_PATH?: string | undefined;
    STORAGE_TYPE?: "file" | "postgres" | "memory" | "mdc" | "elasticsearch" | undefined;
    STREAMING_CHUNK_SIZE?: number | undefined;
    STREAMING_ENABLED?: boolean | undefined;
    STREAMING_MAX_TOKENS?: number | undefined;
    VERSION?: string | undefined;
    redis?: {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    } | undefined;
}>;
/**
 * Loads and validates the server configuration from environment variables using Zod.
 * Throws a clear error and exits if validation fails.
 */
export declare function loadConfig(): EnvVars;
export declare const config: {
    BACKUPS_DIR: string;
    HOST: string;
    HTTP_SERVER: boolean;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    MCP_SERVER: boolean;
    NAME: string;
    PORT: number;
    PROMPTS_DIR: string;
    STORAGE_TYPE: "file" | "postgres" | "memory" | "mdc" | "elasticsearch";
    VERSION: string;
    CORS_ORIGIN?: string | undefined;
    ELASTICSEARCH_INDEX?: string | undefined;
    ELASTICSEARCH_NODE?: string | undefined;
    ELASTICSEARCH_PASSWORD?: string | undefined;
    ELASTICSEARCH_SEQUENCE_INDEX?: string | undefined;
    ELASTICSEARCH_USERNAME?: string | undefined;
    ELEVENLABS_API_KEY?: string | undefined;
    ELEVENLABS_CACHE_DIR?: string | undefined;
    ELEVENLABS_MODEL_ID?: string | undefined;
    ELEVENLABS_OPTIMIZATION_LEVEL?: "speed" | "quality" | "balanced" | undefined;
    ELEVENLABS_SIMILARITY_BOOST?: number | undefined;
    ELEVENLABS_SPEAKER_BOOST?: boolean | undefined;
    ELEVENLABS_STABILITY?: number | undefined;
    ELEVENLABS_STYLE?: number | undefined;
    ELEVENLABS_USE_CACHING?: boolean | undefined;
    ELEVENLABS_VOICE_ID?: string | undefined;
    ENABLE_SSE?: boolean | undefined;
    MDC_BACKUP_ENABLED?: boolean | undefined;
    MDC_BACKUP_INTERVAL?: number | undefined;
    MDC_RULES_DIR?: string | undefined;
    POSTGRES_DATABASE?: string | undefined;
    POSTGRES_HOST?: string | undefined;
    POSTGRES_MAX_CONNECTIONS?: number | undefined;
    POSTGRES_PASSWORD?: string | undefined;
    POSTGRES_PORT?: number | undefined;
    POSTGRES_SSL?: boolean | undefined;
    POSTGRES_USER?: string | undefined;
    SEQUENCES_MAX_STEPS?: number | undefined;
    SEQUENCES_RETRY_ATTEMPTS?: number | undefined;
    SEQUENCES_TIMEOUT?: number | undefined;
    SSE_PATH?: string | undefined;
    STREAMING_CHUNK_SIZE?: number | undefined;
    STREAMING_ENABLED?: boolean | undefined;
    STREAMING_MAX_TOKENS?: number | undefined;
    redis?: {
        db?: number | undefined;
        host?: string | undefined;
        password?: string | undefined;
        port?: number | undefined;
        ttl?: number | undefined;
    } | undefined;
};
