name: Cross-Repo Integration Tests

on:
  repository_dispatch:
    types: [subrepo-updated]

jobs:
  integration-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [mcp-prompts-catalog, mcp-prompts-contracts, mcp-prompts-ts, mcp-prompts-rs]
    steps:
      - name: Skip triggering repo
        if: github.event.client_payload.repo == format('sparesparrow/{0}', matrix.repo)
        run: echo "Skipping tests for triggering repo ${{ matrix.repo }}"
        continue-on-error: true

      - name: Checkout ${{ matrix.repo }}
        if: github.event.client_payload.repo != format('sparesparrow/{0}', matrix.repo)
        uses: actions/checkout@v4
        with:
          repository: sparesparrow/${{ matrix.repo }}
          ref: main

      - name: Run integration tests
        if: github.event.client_payload.repo != format('sparesparrow/{0}', matrix.repo)
        run: |
          if [ -f ./scripts/test-integration.sh ]; then
            bash ./scripts/test-integration.sh
          elif [ -f package.json ]; then
            npm ci
            npm run test:integration || npm test
          else
            echo "No integration test script found." 