name: Multi-Repo Orchestration

on:
  repository_dispatch:
    types: [package_published]
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'update-matrix'
        type: choice
        options:
        - update-matrix
        - build-suite
        - generate-release-notes

jobs:
  update-compatibility-matrix:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' || github.event.inputs.action == 'update-matrix'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Generate compatibility matrix
      run: |
        node scripts/generate-matrix.js
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/compatibility-matrix.md
        git commit -m "docs: update compatibility matrix" || exit 0
        git push

  build-suite-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' || github.event.inputs.action == 'build-suite'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build suite image
      run: |
        docker build -f docker/Dockerfile.suite -t sparesparrow/mcp-prompts-suite:${{ github.sha }} .
        docker push sparesparrow/mcp-prompts-suite:${{ github.sha }}
    
    - name: Update suite image tag
      if: github.event_name == 'repository_dispatch'
      run: |
        docker tag sparesparrow/mcp-prompts-suite:${{ github.sha }} sparesparrow/mcp-prompts-suite:latest
        docker push sparesparrow/mcp-prompts-suite:latest

  generate-release-notes:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' || github.event.inputs.action == 'generate-release-notes'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Generate release notes
      run: |
        node scripts/generate-release-notes.js
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/release-notes.md
        git commit -m "docs: update release notes" || exit 0
        git push 